config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  resources :users
  resources :events
  root "sessions#new"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attended_event.rb
# frozen_string_literal: true

class AttendedEvent < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
  validates :attendee_id, presence: true
  validates :attended_event_id, presence: true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  include EventsHelper
  belongs_to :creator, class_name: 'User'
  has_many :attendees,
           class_name: 'AttendedEvent',
           foreign_key: 'attended_event_id',
           dependent: :destroy
  validates :description, presence: true, length: { maximum: 100 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include EventsHelper
  has_many :events, foreign_key: 'creator_id', dependent: :destroy
  has_many :attendedevents, class_name: 'AttendedEvent', foreign_key: 'attendee_id', dependent: :destroy
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 40 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/attended_events_controller.rb
# frozen_string_literal: true

class AttendedEventsController < ApplicationController
  def new
    @attendance = AttendedEvent.new
  end

  def create
    @attendance = AttendedEvent.new(attendance_params)
    @attendance.save
  end

  private

  def attendance_params
    params.require(:attendance).permit(:attendee_id, :attendedevent_id)
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def new
    @event = Event.new
    @user = current_user
  end

  def create
    @event = current_user.events.build(event_params)
    @user = current_user
    if @event.save
      @event.attendees.create(attendee_id: current_user.id)
      redirect_to @event
    else
      render 'events/new'
    end
  end

  def show
    @event = Event.find_by(id: params[:id])
    @user = @event.creator
    @attendees = @event.attendees
  end

  def destroy; end

  def index
    @events = Event.all
    @upcoming_events = self.upcoming_events
    @prev_events = self.prev_events
  end

  def upcoming_events
    Event.where('date > ?', Time.now)
  end

  def prev_events
    Event.where('date < ?', Time.now)
  end

  private

  def event_params
    params.require(:event).permit(:description, :date)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(name: params[:session][:name])
    if user
      log_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid Username'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @events = @user.events
    @upcoming_events = current_user.upcoming_events
    @prev_events = current_user.prev_events
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/attended_events_helper.rb
# frozen_string_literal: true

module AttendedEventsHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
  def upcoming_events
    Event.where('date > ?', Time.now)
  end

  def prev_events
    Event.where('date < ?', Time.now)
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      @current_user = User.find_by(id: user_id)
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Forgets a persistent session.
  def forget(_user)
    cookies.delete(:user_id)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/attended_events/_attended_event.html.erb
<span class="content">
  <%= User.find(attended_event.attendee_id).name %> <br>  
</span>

app/views/events/_event.html.erb
<span class="content">
    <%= link_to event.description, event %> <br>    
  </span>

app/views/events/_upcoming.html.erb
<div class="ev-list">
  <h3>Upcoming Events</h3>
  <% if @upcoming_events.any? %>
    <ol class="events">
      <% @upcoming_events.each do |event| %>
        <li><%= render event %></li>
      <% end %>
    </ol>
  <% end %>
</div>
<div class="ev-list">
  <h3>Previous Events</h3>
  <% if @prev_events.any? %>
    <ol class="events">
    <% @prev_events.each do |event| %>
      <li><%= render event %></li>
    <% end %>
    </ol>
  <% end %>
</div>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/index.html.erb
<div class="main">
  <h1>Events</h1>
  <%= render 'events/upcoming' %>
</div>

app/views/events/new.html.erb
<div class="form">
  <h1>Create a new event, <%= @user.name %></h1><br>
  <% provide(:button_text, 'Create') %>
  <%= render 'layouts/event-form', url: new_event_path(@event) %>
<div>

app/views/events/show.html.erb
<div class="main">
  <h1><%= @event.description %></h1>
  <% if @event.attendees.any? %>
    <p class="atd">Number of attendees: <%= @event.attendees.count %></h3>
    <p>Event attendees are as follows:</p>
    <ol class="attendees">
      <% @attendees.each do |attendee| %>
        <li><%= render attendee %></li>
      <% end %>
    </ol>
  <% end %>
</div>

app/views/layouts/_event-form.html.erb
<%= form_for(@event) do |f| %>
  <%= f.label :date, class: "form-label" %>
  <%= f.date_select :date, placeholder: "mm/dd/yyyy", class: "form-text" %><br>

  <%= f.label :description, class: "form-label" %>
  <%= f.text_field :description, placeholder: "Enter event description", class: "form-text" %><br>

  <%= f.submit yield(:button_text), class: 'form-btn' %>
<% end %>

app/views/layouts/_form.html.erb
<%= form_for(@user) do |f| %>

  <%= f.label :name, class: "form-label" %>
  <%= f.text_field :name, class: "form-text" %><br>

  <%= f.label :email, class: "form-label" %>
  <%= f.email_field :email, class: "form-text" %><br>

  <%= f.submit yield(:button_text), class: 'form-btn' %>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <% if logged_in? %>
    <span><%= link_to "Log out", logout_path, method: :delete %></span>
    <% if action_name == "index" %>
      <span><%= link_to "Profile", current_user %></span>
    <% elsif action_name == "show" %>
      <span><%= link_to "Events", events_path %></span>
    <% end %>
  <% else %>
    <span><%= link_to "Sign up", signup_path %></span>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= render 'layouts/header' %>
      <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<% provide(:button_text, 'Sign up') %>
<div class="form">
  <h1>SIGN UP</h1><br>
  <%= render 'layouts/form', url: signup_path(@user) %>
</div>

app/views/users/show.html.erb
<div class="main">
  <% provide(:button_text, 'Create an Event') %>
  <div class="create">
    <h1><%= @user.name %></h1>
    <%= link_to 'Create a new event', new_event_path %>
  </div>
  <%= render 'events/upcoming' %>
</div>